# -*- coding: utf-8 -*-
"""HW4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-bBhSHSakkMWpHBjzLnY_XX2eGL75C2S
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q requests streamlit pandas plotly

import json
import requests

# 中央氣象署農業氣象預報 API（F-A0010-001）
url = "https://opendata.cwa.gov.tw/fileapi/v1/opendataapi/F-A0010-001?Authorization=CWA-E5768D09-F706-4753-B388-9C6A8905AB97&downloadType=WEB&format=JSON"

# 發送請求
response = requests.get(url)

# 將回傳內容轉為 JSON
data = response.json()

# 提取主資料部分（可視為一週農業氣象預報）
main_data = data["cwaopendata"]["resources"]["resource"]["data"]["agrWeatherForecasts"]

# 使用 json.dumps 顯示整體結構（保留中文，排版清晰）
print(json.dumps(main_data, indent=4, ensure_ascii=False))

import json
import requests

# API 來源（你提供的 URL）
url = "https://opendata.cwa.gov.tw/fileapi/v1/opendataapi/F-A0010-001?Authorization=CWA-3DE12743-8E82-4A80-9524-AC203C066CA5&downloadType=WEB&format=JSON"

# 發送請求取得資料
response = requests.get(url)
data = response.json()

# 擷取六大地區資料
locations = data["cwaopendata"]["resources"]["resource"]["data"]["agrWeatherForecasts"]["weatherForecasts"]["location"]

# 結果儲存
temperature_extremes = {}

# 分析每個地區的溫度
for loc in locations:
    region_name = loc["locationName"]
    max_temps = [int(day["temperature"]) for day in loc["weatherElements"]["MaxT"]["daily"]]
    min_temps = [int(day["temperature"]) for day in loc["weatherElements"]["MinT"]["daily"]]

    # 找出最高溫與最低溫及其對應日期
    max_temp = max(max_temps)
    min_temp = min(min_temps)
    max_date = loc["weatherElements"]["MaxT"]["daily"][max_temps.index(max_temp)]["dataDate"]
    min_date = loc["weatherElements"]["MinT"]["daily"][min_temps.index(min_temp)]["dataDate"]

    temperature_extremes[region_name] = {
        "最高氣溫": {
            "日期": max_date,
            "溫度": f"{max_temp}°C"
        },
        "最低氣溫": {
            "日期": min_date,
            "溫度": f"{min_temp}°C"
        }
    }

# 輸出 JSON 結構，觀察資料（符合作業要求）
print(json.dumps(temperature_extremes, indent=2, ensure_ascii=False))

response = requests.get(url)
data = response.json()

import sqlite3
# --- 2. 建立 SQLite 資料庫與資料表 ---
conn = sqlite3.connect("data.db")
cursor = conn.cursor()


# 建立 Table：TemperatureForecasts
cursor.execute("""
CREATE TABLE IF NOT EXISTS TemperatureForecasts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    regionName TEXT,
    dataDate TEXT,
    mint INTEGER,
    maxt INTEGER
)
""")

# 清空舊資料（避免重複）
cursor.execute("DELETE FROM TemperatureForecasts")

# 插入資料
for loc in locations:
    region = loc["locationName"]
    maxT_list = loc["weatherElements"]["MaxT"]["daily"]
    minT_list = loc["weatherElements"]["MinT"]["daily"]

    for i in range(len(maxT_list)):
        date = maxT_list[i]["dataDate"]
        maxt = int(maxT_list[i]["temperature"])
        mint = int(minT_list[i]["temperature"])
        cursor.execute("""
            INSERT INTO TemperatureForecasts (regionName, dataDate, mint, maxt)
            VALUES (?, ?, ?, ?)
        """, (region, date, mint, maxt))

conn.commit()

conn.close()

import sqlite3
import pandas as pd

# 連線到資料庫
conn = sqlite3.connect("data.db")

# 查詢資料表所有內容
df = pd.read_sql_query("SELECT * FROM TemperatureForecasts", conn)

# 顯示資料
print(df)

conn.close()

import sqlite3
import pandas as pd

# 連接 SQLite 資料庫
conn = sqlite3.connect("data.db")
cursor = conn.cursor()

# 查詢所有地區名稱
df_regions = pd.read_sql_query("SELECT DISTINCT regionName FROM TemperatureForecasts", conn)
print("✅ 所有地區名稱：")
print(df_regions)

# 查詢中部地區的所有氣溫資料
df_central = pd.read_sql_query("SELECT * FROM TemperatureForecasts WHERE regionName='中部地區'", conn)
print("\n✅ 中部地區氣溫資料：")
print(df_central)

conn.close()

# app.py
import streamlit as st
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'Microsoft JhengHei'  # 微軟正黑體，支援中文


# 設定標題
st.title("🌤️ 一週氣溫預報查詢系統")

# 連線至 SQLite 資料庫
conn = sqlite3.connect("data.db")
cursor = conn.cursor()

# 取得所有地區名稱
regions = pd.read_sql_query("SELECT DISTINCT regionName FROM TemperatureForecasts", conn)
region_list = regions["regionName"].tolist()

# 地區下拉選單
selected_region = st.selectbox("請選擇地區", region_list)

# 查詢所選地區的氣溫資料
query = """
SELECT dataDate, mint, maxt
FROM TemperatureForecasts
WHERE regionName = ?
ORDER BY dataDate
"""
df = pd.read_sql_query(query, conn, params=(selected_region,))

# 顯示表格
st.subheader(f"{selected_region} 一週氣溫資料表")
st.dataframe(df)

# 顯示折線圖
st.subheader("溫度趨勢圖（最高與最低氣溫）")
fig, ax = plt.subplots()
ax.plot(df["dataDate"], df["maxt"], marker='o', label="最高氣溫")
ax.plot(df["dataDate"], df["mint"], marker='o', label="最低氣溫")
ax.set_ylabel("氣溫 (°C)")
ax.set_xlabel("日期")
ax.set_title(f"{selected_region} 一週氣溫趨勢")
plt.xticks(rotation=45)
plt.grid(True)
plt.legend()
st.pyplot(fig)

conn.close()